services:
  # ========== BASE DE DATOS ==========
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: delivereats_user
      POSTGRES_PASSWORD: delivereats/22418
      POSTGRES_DB: delivereats_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    networks:
      - delivereats-network

  postgres-catalog:
    image: postgres:16
    environment:
      POSTGRES_USER: delivereats_user
      POSTGRES_PASSWORD: delivereats/22418
      POSTGRES_DB: delivereats_catalog
    ports:
      - "5433:5432"
    volumes:
      - pgdata-catalog:/var/lib/postgresql/data
    networks:
      - delivereats-network

  postgres-orders:
    image: postgres:16
    environment:
      POSTGRES_USER: delivereats_user
      POSTGRES_PASSWORD: delivereats/22418
      POSTGRES_DB: delivereats_orders
    ports:
      - "5434:5432"
    volumes:
      - pgdata-orders:/var/lib/postgresql/data
    networks:
      - delivereats-network

  # ========== MICROSERVICIOS ==========
  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres
    ports:
      - "50051:50051"
    volumes:
      - ./proto:/app/proto:ro
    networks:
      - delivereats-network

  catalog-service:
    build: ./catalog-service
    env_file:
      - ./catalog-service/.env
    depends_on:
      - postgres-catalog
    ports:
      - "50052:50052"
    volumes:
      - ./proto:/app/proto:ro
    networks:
      - delivereats-network

  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    depends_on:
      - postgres-orders
      - catalog-service
    ports:
      - "3001:3001"
    volumes:
      - ./proto:/app/proto:ro
    networks:
      - delivereats-network

  gateway:
    build: ./gateway
    env_file:
      - ./gateway/.env
    depends_on:
      - auth-service
      - order-service
    ports:
      - "3000:3000"
    volumes:
      - ./proto:/app/proto:ro
    networks:
      - delivereats-network

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway
    networks:
      - delivereats-network

volumes:
  pgdata-auth:
  pgdata-catalog:
  pgdata-orders:

networks:
  delivereats-network:
    driver: bridge